// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDIY-2sI7jwz7_VMsvFAXfkNfoXW2_GJs',
    appId: '1:336348591093:web:165106e20017eb3269a6bc',
    messagingSenderId: '336348591093',
    projectId: 'trendharbor-6fafc',
    authDomain: 'trendharbor-6fafc.firebaseapp.com',
    storageBucket: 'trendharbor-6fafc.firebasestorage.app',
    measurementId: 'G-80SRTFW9TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxZSyi1mvNhWUvs0xceFvyDrSaPk_3qHo',
    appId: '1:336348591093:android:ec857f72ce9e444a69a6bc',
    messagingSenderId: '336348591093',
    projectId: 'trendharbor-6fafc',
    storageBucket: 'trendharbor-6fafc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPpIUx4-gDfS0MA-oJt7Hx6OLyN4eJdMY',
    appId: '1:336348591093:ios:2753bd25ae4f534269a6bc',
    messagingSenderId: '336348591093',
    projectId: 'trendharbor-6fafc',
    storageBucket: 'trendharbor-6fafc.firebasestorage.app',
    iosBundleId: 'com.example.trendharborV2',
  );
}
